#
# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

# Input files
noisybw: "None"
cleanbw: "None"
cleanpeakfile: "None"
read_buffer: 1000
pad: 5000
regions: "None"
# Data Pre-processing parameters
interval_size: 50000
genome: "hg19"

# Experiment args
peaks: False
tracks: False
task: "both"
batch_size: 512
num_workers: 4
weights_path: "None"
seed: 42

# Data processing args
pad: 5000
layers: "None"

#Infer args
intervals_file: "None"
genome: "None"
reg_rounding: 0
threshold: 0.5
batches_per_worker: 16

# Output file args
gen_bigwig: True
deletebg: False
out_resolution: "None"

# Advanced torch distributed args
dist-url: 'tcp://127.0.0.1:4321'
dist-backend: 'gloo'

# ADVANCED OPTIONS
layersbw: "None"
layers: "None"
denoise_h5_files: "None"
intervals_file: "None"

#Eval options
best_metric_choice: "AUROC"
