#
# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

# Experiment args
out_home: './'
label: 'inference_output'
# If both peaks and tracks are False, then the program enters into a default mode and outputs both.
# If both peaks and tracks are True, then the program outputs both.
# If either one of them is True, then only the corresponding denoised output is saved.
peaks: False
tracks: False
# Task is the task that model was trained for. If the task is regression, then model cannot
# output denosied peaks. Similarly, if the task is classification, then model cannot 
# output denoised tracks. The above peaks, tracks options only are relevant if task is "both".
task: "both"
print_freq: 50
bs: 512
num_workers: 4
weights_path: "None"
# ID of the GPU to be used. Only relevant if running atacworks in single GPU mode.
# If using multi-GPU mode i.e., if --distributed True, then this option is irrelevant. 
# All available GPUs on the system are used in multi-GPU setting.
gpu_idx: 0
distributed: False
dist-url: 'tcp://127.0.0.1:4321'
dist-backend: 'gloo'
seed: 42
debug: False

# Data processing args
pad: 5000
transform: "None"
layers: "None"

#Infer args
input_files: "None"
intervals_file: "None"
sizes_file: "None"
reg_rounding: 0
cla_rounding: 3
infer_threshold: 0.5
batches_per_worker: 16

# Output file args
result_fname: inferred
gen_bigwig: True
deletebg: False
